version: '3'

services:

  test:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile
    #volumes:
    #  - '.:/app'
    #  - './node_modules:/app/node_modules'
    ports:
      - 3000:3000
    #environment:
    #  - CHOKIDAR_USEPOLLING=true
